[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "development"

[build.processing]
  skip_processing = true

# Force new deployment
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 